In [1]:
!pip install flair

     |████████████████████████████████| 450kB 5.3MB/s 
     |████████████████████████████████| 1.3MB 8.2MB/s 
     |████████████████████████████████| 19.7MB 9.4MB/s 
     |████████████████████████████████| 71kB 7.6MB/s 
     |████████████████████████████████| 1.1MB 30.0MB/s 
     |████████████████████████████████| 983kB 14.6MB/s 
     |████████████████████████████████| 798kB 50.0MB/s 
     |████████████████████████████████| 890kB 26.4MB/s 
     |████████████████████████████████| 2.9MB 37.4MB/s 
  Created wheel for ftfy: filename=ftfy-5.8-cp36-none-any.whl size=45613 sha256=6f3d667fb78a085e6e5cb4d8a013e0d5b13d4f7bc32730cb9bfd54a1a767e18b
  Stored in directory: /root/.cache/pip/wheels/ba/c0/ef/f28c4da5ac84a4e06ac256ca9182fc34fa57fefffdbc68425b
  Created wheel for segtok: filename=segtok-1.5.10-cp36-none-any.whl size=25020 sha256=9a5134c547b278305e2c762e11c8f7697327d1d65df583e48b29584edd779c07
  Stored in directory: /root/.cache/pip/wheels/b4/39/f6/9ca1c5cabde964d728023b5751c3a206a5c8cc40

In [2]:
import numpy as np
from flair.embeddings import WordEmbeddings
from flair.embeddings import TransformerWordEmbeddings
from flair.data import Sentence
from scipy.spatial import distance

In [4]:
glove_embedding = WordEmbeddings('glove')

2020-12-15 16:12:23,845 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim.vectors.npy not found in cache, downloading to /tmp/tmpm20u3hj6


100%|██████████| 160000128/160000128 [00:17<00:00, 9301680.58B/s]

2020-12-15 16:12:41,901 copying /tmp/tmpm20u3hj6 to cache at /root/.flair/embeddings/glove.gensim.vectors.npy


2020-12-15 16:12:42,133 removing temp file /tmp/tmpm20u3hj6
2020-12-15 16:12:43,760 https://flair.informatik.hu-berlin.de/resources/embeddings/token/glove.gensim not found in cache, downloading to /tmp/tmp0l6otxeo


100%|██████████| 21494764/21494764 [00:03<00:00, 5407705.89B/s]

2020-12-15 16:12:48,593 copying /tmp/tmp0l6otxeo to cache at /root/.flair/embeddings/glove.gensim
2020-12-15 16:12:48,621 removing temp file /tmp/tmp0l6otxeo


In [6]:
sen = Sentence('apple released iphone 12 pro max in 2020')
glove_embedding.embed(sen)

[Sentence: "apple released iphone 12 pro max in 2020"   [− Tokens: 8]]

In [7]:

for token in sen:
  print(token)
  print(token.embedding)
  print('\n')

Token: 1 apple
tensor([-0.5985, -0.4632,  0.1300, -0.0196,  0.4603, -0.3018,  0.8977, -0.6563,
         0.6686, -0.4916,  0.0376, -0.0509,  0.6451, -0.5388, -0.3765, -0.0431,
         0.5138,  0.1778,  0.2860,  0.9206, -0.4935, -0.4858,  0.6132,  0.7821,
         0.1925,  0.9123, -0.0556, -0.1251, -0.6569,  0.0686,  0.5563,  1.6110,
        -0.0074, -0.4888,  0.4549,  0.9610, -0.0634,  0.1743,  0.9814, -1.3125,
        -0.1580, -0.5430, -0.1389, -0.2615, -0.3691,  0.2684, -0.2438, -0.1948,
         0.6258, -0.7377,  0.3835, -0.7500, -0.3905,  0.0915, -0.3659, -1.4715,
        -0.4523,  0.2256,  1.1412, -0.3853, -0.0672,  0.5729, -0.3919,  0.3130,
        -0.2923, -0.9616,  0.1515, -0.2166,  0.2510,  0.0970,  0.2843,  1.4296,
        -0.5056, -0.5137, -0.4722,  0.3204,  0.0231,  0.2262, -0.0972,  0.8213,
         0.9260, -1.0086, -0.3864,  0.8641, -1.2060, -0.2853,  0.2265, -0.3877,
         0.4088,  0.5930,  0.3077,  0.8380, -0.6366, -0.4464, -0.4341, -0.7936,
        -0.2867, -0.0344,

In [8]:

sen1 = Sentence('an apple a day keeps doctor away')
glove_embedding.embed(sen1)

[Sentence: "an apple a day keeps doctor away"   [− Tokens: 7]]

In [10]:
for t in sen1:
  print(t)
  print(t.embedding)
  print('\n')

Token: 1 an
tensor([-0.4214, -0.1880,  0.4624, -0.1761,  0.3621,  0.3670,  0.2792,  0.1463,
        -0.0542,  0.4583,  0.0654, -0.3372,  0.0675, -0.3632,  0.5030, -0.0104,
         0.7283, -0.1756, -0.3400,  0.0729,  0.6448, -0.2391,  0.3838,  0.1386,
         1.0994, -0.2488, -0.1508, -0.4874, -0.2304,  0.0648, -0.7018,  0.8265,
         0.0613,  0.1853, -0.3016, -0.0222,  0.3430,  0.8033,  0.1714,  0.1546,
        -0.5076,  0.3957,  0.0543, -0.5308,  0.4825,  0.0862,  0.5958, -0.2238,
        -0.3955, -0.7304, -0.1028, -0.3917,  1.2290,  1.2129, -1.0365, -3.4971,
         0.1092, -1.0084,  1.9998,  0.7964,  0.3881,  0.4375,  0.0852,  0.3855,
         0.6199, -1.0320,  0.7012, -0.2246,  0.0794,  0.0913, -0.2120, -0.5543,
        -0.0534, -0.8020,  0.4680, -0.0501, -0.5742, -0.0848, -1.7227, -0.9429,
         0.9867,  0.3121, -0.3774,  0.0687, -0.7784, -0.2849,  0.8105,  0.4660,
        -0.1186, -0.9341,  0.3372,  0.0379, -0.1827, -0.0199,  0.2049, -0.4772,
        -0.4925, -0.5652,  0

In [11]:
# Glove does not understand the context 
glove_dist = distance.euclidean(np.array(sen[0].embedding),np.array(sen1[1].embedding))
print('Distance between apple embeddings for Glove = {}'.format(glove_dist))

Distance between apple embeddings for Glove = 0.0


#Best Embeddings

In [16]:
best_embedding = TransformerWordEmbeddings('bert-base-multilingual-cased')

In [18]:
best_embedding = TransformerWordEmbeddings('bert-base-multilingual-cased')
best_embedding.embed(sen)
for token in sen:
  print(token)
  print(token.embedding)

Token: 1 apple
tensor([-0.5985, -0.4632,  0.1300,  ...,  1.4355,  0.0781,  0.2832])
Token: 2 released
tensor([-0.0451, -0.7260,  0.6271,  ...,  0.8646,  0.4700,  0.4862])
Token: 3 iphone
tensor([-0.3609, -0.5975,  0.5235,  ...,  0.8601,  0.1087, -0.7263])
Token: 4 12
tensor([ 0.0730,  0.1813,  0.0204,  ...,  1.0590,  0.4350, -0.1114])
Token: 5 pro
tensor([-0.2332,  0.1988, -0.2101,  ...,  1.8614,  0.7496, -0.2961])
Token: 6 max
tensor([ 0.3356,  0.1247,  0.2099,  ...,  1.3470, -0.0816,  0.4086])
Token: 7 in
tensor([ 0.0857, -0.2220,  0.1657,  ...,  1.4064, -0.2576, -0.0673])
Token: 8 2020
tensor([-0.1241,  0.3447,  0.9852,  ...,  0.8098,  1.0564, -0.2190])


In [19]:

best_embedding.embed(sen1)
for token in sen1:
  print(token)
  print(token.embedding)

Token: 1 an
tensor([-0.4214, -0.1880,  0.4624,  ...,  1.1509,  0.7702,  0.1811])
Token: 2 apple
tensor([-0.5985, -0.4632,  0.1300,  ...,  1.6751,  0.9633,  0.1804])
Token: 3 a
tensor([-0.2709,  0.0440, -0.0203,  ...,  0.8785, -0.3684,  0.5002])
Token: 4 day
tensor([-0.3669,  0.4154,  0.1348,  ...,  0.8774, -0.1257, -0.0460])
Token: 5 keeps
tensor([-0.2821,  0.0814,  1.0041,  ..., -0.4352,  0.8831,  0.0468])
Token: 6 doctor
tensor([ 0.0432, -0.4753,  0.1581,  ...,  0.3483, -0.2896,  0.3766])
Token: 7 away
tensor([-0.1038, -0.0148,  0.5993,  ...,  0.1684,  0.2573,  0.2163])


In [21]:

# Glove does not understand the context 
bert_dist = distance.euclidean(np.array(sen[0].embedding),np.array(sen1[1].embedding))
print('Distance between apple embeddings for BERT = {}'.format(bert_dist))

Distance between apple embeddings for BERT = 42.60582733154297
